
package com.tcs.sample.documentstyle.endpointimplementation;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.tcs.sample.documentstyle.endpointinterface.UserAccount;
import com.tcs.sample.documentstyle.endpointinterface.UserDetails;
import com.tcs.sample.documentstyle.endpointinterface.UserResponse;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://endpointInterface.documentStyle.sample.tcs.com/")
public interface HelloWorld {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://endpointInterface.documentStyle.sample.tcs.com/", className = "com.tcs.sample.documentstyle.endpointinterface.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://endpointInterface.documentStyle.sample.tcs.com/", className = "com.tcs.sample.documentstyle.endpointinterface.GetHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

    /**
     * 
     * @param userAccount
     * @param userDetails
     * @return
     *     returns com.tcs.sample.documentstyle.endpointinterface.UserResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsObject", targetNamespace = "http://endpointInterface.documentStyle.sample.tcs.com/", className = "com.tcs.sample.documentstyle.endpointinterface.GetHelloWorldAsObject")
    @ResponseWrapper(localName = "getHelloWorldAsObjectResponse", targetNamespace = "http://endpointInterface.documentStyle.sample.tcs.com/", className = "com.tcs.sample.documentstyle.endpointinterface.GetHelloWorldAsObjectResponse")
    public UserResponse getHelloWorldAsObject(
        @WebParam(name = "userDetails", targetNamespace = "")
        UserDetails userDetails,
        @WebParam(name = "userAccount", targetNamespace = "")
        UserAccount userAccount);

}
