//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.02 at 06:48:09 PM IST 
//


package com.tcs.sample.rest.webserviceProvider.provider;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.tcs.sample.rest.webserviceProvider.stubs.userdetailsdocument.Address;
import com.tcs.sample.rest.webserviceProvider.stubs.userdetailsdocument.UserDetails;
import com.tcs.sample.rest.webserviceProvider.stubs.userdetailsresponsedocument.UserDetailsResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the userdetailsdocument package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _UserDetailsDocument_QNAME = new QName("urn:UserDetailsDocument", "UserDetailsDocument");
	private final static QName _UserDetailsResponseDocument_QNAME = new QName("urn:UserDetailsResponseDocument", "UserDetailsResponseDocument");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: userdetailsdocument
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link UserDetails }
	 * 
	 */
	public UserDetails createUserDetails() {
		return new UserDetails();
	}

	/**
	 * Create an instance of {@link Address }
	 * 
	 */
	public Address createAddress() {
		return new Address();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UserDetails }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:UserDetailsDocument", name = "UserDetailsDocument")
	public JAXBElement<UserDetails> createUserDetailsDocument(UserDetails value) {
		return new JAXBElement<UserDetails>(_UserDetailsDocument_QNAME, UserDetails.class, null, value);
	}

	/**
	 * Create an instance of {@link UserDetailsResponse }
	 * 
	 */
	public UserDetailsResponse createUserDetailsResponse() {
		return new UserDetailsResponse();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UserDetailsResponse }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:UserDetailsResponseDocument", name = "UserDetailsResponseDocument")
	public JAXBElement<UserDetailsResponse> createUserDetailsResponseDocument(UserDetailsResponse value) {
		return new JAXBElement<UserDetailsResponse>(_UserDetailsResponseDocument_QNAME, UserDetailsResponse.class, null, value);
	}

}
