
package com.tcs.sample.rpcstyle.endpointimplementation;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://endpointInterface.rpcStyle.sample.tcs.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {


	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getHelloWorldAsString(
			@WebParam(name = "arg0", partName = "arg0")
			String arg0);

}
